export const carModels = {
  Acura: ["MDX", "RDX", "TLX", "ILX", "NSX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "4C", "Giulietta"],
  "Aston Martin": ["DB11", "Vantage", "DBS Superleggera", "Rapide"],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "R8"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  BMW: ["3 Series", "5 Series", "7 Series", "X3", "X5", "X7", "Z4", "i3", "i8"],
  Bugatti: ["Chiron", "Veyron", "Divo"],
  Buick: ["Encore", "Enclave", "Regal", "LaCrosse"],
  Cadillac: ["CTS", "XTS", "Escalade", "CT6"],
  Chevrolet: [
    "Camaro",
    "Corvette",
    "Malibu",
    "Silverado",
    "Equinox",
    "Traverse",
  ],
  Chrysler: ["300", "Pacifica"],
  Citroën: ["C3", "C4", "C5", "Berlingo"],
  Dodge: ["Charger", "Challenger", "Durango", "Journey"],
  Ferrari: ["488", "812 Superfast", "Portofino", "SF90 Stradale"],
  Fiat: ["500", "500X", "500L", "124 Spider"],
  Ford: ["Mustang", "F-150", "Focus", "Escape", "Explorer", "Expedition"],
  Genesis: ["G70", "G80", "G90"],
  GMC: ["Sierra", "Yukon", "Terrain", "Acadia"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "Odyssey"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
  Jaguar: ["XE", "XF", "F-PACE", "F-TYPE", "I-PACE"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade"],
  Kia: ["Forte", "Optima", "Sorento", "Sportage", "Telluride"],
  Koenigsegg: ["Agera", "Regera", "Jesko"],
  Lamborghini: ["Huracán", "Aventador", "Urus"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Discovery", "Defender"],
  Lexus: ["IS", "ES", "RX", "NX", "GX", "LX", "LC", "LS"],
  Lincoln: ["Continental", "Navigator", "Aviator", "Nautilus"],
  Lotus: ["Evora", "Elise", "Exige"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "GranTurismo"],
  Mazda: ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5"],
  McLaren: ["570S", "720S", "Senna", "GT"],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
  ],
  MINI: ["Cooper", "Clubman", "Countryman"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "Eclipse Cross"],
  Nissan: [
    "Altima",
    "Maxima",
    "Sentra",
    "Rogue",
    "Murano",
    "Pathfinder",
    "Armada",
    "GT-R",
  ],
  Pagani: ["Huayra", "Zonda"],
  Peugeot: ["208", "308", "3008", "5008"],
  Porsche: ["911", "Panamera", "Cayenne", "Macan", "Boxster", "Cayman"],
  Ram: ["1500", "2500", "3500"],
  Renault: ["Clio", "Megane", "Captur", "Kadjar", "Talisman"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan"],
  Saab: ["9-3", "9-5"],
  Subaru: ["Impreza", "Legacy", "Forester", "Outback", "Crosstrek"],
  Suzuki: ["Swift", "Vitara", "Jimny"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Roadster"],
  Toyota: [
    "Corolla",
    "Camry",
    "Rav4",
    "Highlander",
    "4Runner",
    "Sienna",
    "Tundra",
    "Tacoma",
    "Supra",
  ],
  Volkswagen: ["Golf", "Jetta", "Passat", "Tiguan", "Atlas", "Touareg"],
  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
};

export const carBrands = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Pagani",
  "Peugeot",
  "Porsche",
  "Ram",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const types = [
  "Sedan",
  "Sports",
  "Coupe",
  "Minivan",
  "Pickup",
  "Station Wagon",
];

export const fuels = ["Gas", "Diesel", "Electric"];
